### ISSUE TITLE
Sync product status with Default Stock only

### ISSUE THREAD

**Issue by Bitchiceo** [magefan/module-facebook-pixel#1]
Magento 2.4.3-p1
Stock : **Default** -> Default Source (Inactive)
            **Store** -> A + B + C + D Source (Active)
Stock Store with 4 inventory sources is selected for Main Website base (only one website) and products

Extension uses Default Source to update product inventory giving "out-of-stock" label to every product.  Default source is not the active product source for the website though.  When you add an extra Default inventory item it appears to Facebook catalog.

Example:
Product SPACE102
Assigned inventory : A  In Stock  3 Active                   _In stock_ on Main Website and salable - _Out-stock_ in Facebook Catalog

Product Space102
Assigned inventory: A  Out of stock  1 Active                   _Out-of-stock_ on Main Website and not salable
                               + Default Source                                 _in stock_ in Facebook Catalog

Is there any solution?

**Comment by bohdan-berezhniy** [comment]
Hello @Bitchiceo 
We have created an issue for the Facebook team
https://github.com/facebookincubator/facebook-for-magento2/issues/105
We will let you know when this is resolved
